# TODO: create an LLM that execute the code generated by CodeLLM.py
from tools.capture_image import CaptureImage
from tools.check_markers import CheckMarkers
from tools.set_speed import SetSpeed

def calibration_process():
    # Capture image
    image = CaptureImage.call()
    print(f"image: {image}")

    # Check markers
    markers_ok = CheckMarkers.call(image=image)
    print(f"markers_ok: {markers_ok}")

    if markers_ok:
        # Set speed
        speed_set = SetSpeed.call(speed=10000)
        print(f"speed_set: {speed_set}")
        return speed_set

    else:
        return calibration_process()

calibration_process()