[
    ('part_list', 5, 'computedFrom', ['ReceiveOrder', 'call'], [7, 9]), 
    ('ReceiveOrder', 7, 'comesFrom', [], []), 
    ('call', 9, 'comesFrom', [], []), 
    ('executor', 17, 'comesFrom', [], []), 
    ('futures', 19, 'computedFrom', ['executor', 'submit', 'RetrievePartList', 'call', 'part_list', 'part_list', 'executor', 'submit', 'L12SetUp', 'call'], [22, 24, 26, 28, 30, 32, 35, 37, 39, 41]), 
    ('executor', 22, 'comesFrom', ['executor'], [17]), 
    ('submit', 24, 'comesFrom', [], []), 
    ('RetrievePartList', 26, 'comesFrom', [], []), 
    ('call', 28, 'comesFrom', ['call'], [9]), 
    ('part_list', 30, 'comesFrom', ['part_list'], [5]), 
    ('part_list', 32, 'comesFrom', ['part_list'], [5]), 
    ('executor', 35, 'comesFrom', ['executor'], [17]), 
    ('submit', 37, 'comesFrom', ['submit'], [24]), 
    ('L12SetUp', 39, 'comesFrom', [], []), 
    ('call', 41, 'comesFrom', ['call'], [9]), 
    ('future', 45, 'computedFrom', ['futures', 'as_completed'], [47, 49]), 
    ('as_completed', 47, 'comesFrom', ['as_completed'], [47]), 
    ('futures', 49, 'comesFrom', ['futures'], [19]), 
    ('result', 52, 'computedFrom', ['result', 'future'], [54, 56]), 
    ('future', 54, 'comesFrom', ['future'], [45]), 
    ('result', 56, 'comesFrom', ['result'], [52]), 
    ('result', 61, 'comesFrom', ['result'], [52]), 
    ('result', 67, 'comesFrom', ['result'], [52]), 
    ('Exception', 73, 'comesFrom', ['Exception'], [73]), 
    ('assembled', 77, 'computedFrom', ['L12AssembleSpindle', 'call', 'part_list', 'part_list'], [79, 81, 83, 85]), 
    ('L12AssembleSpindle', 79, 'comesFrom', [], []), 
    ('call', 81, 'comesFrom', ['call'], [9]), 
    ('part_list', 83, 'comesFrom', ['part_list'], [5]), 
    ('part_list', 85, 'comesFrom', ['part_list'], [5]), 
    ('assembled', 89, 'comesFrom', ['assembled'], [77]), 
    ('Exception', 95, 'comesFrom', ['Exception'], [73]), 
    ('test_result', 99, 'computedFrom', ['TestSpindle', 'call', 'product_id', '1'], [101, 103, 105, 107]), 
    ('TestSpindle', 101, 'comesFrom', [], []), 
    ('call', 103, 'comesFrom', ['call'], [9]), 
    ('product_id', 105, 'comesFrom', [], []), 
    ('1', 107, 'comesFrom', [], []), 
    ('test_result', 111, 'comesFrom', ['test_result'], [99])
]